name: Conda publication policy

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publication:
    uses: uibcdf/molsyssuite/.github/workflows/check-conda-publication.yaml@2a2a459cc3795bb92766fffa0fe28f4d80f01ad4
